// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "center/Bussinesstype.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cms_8120 {

namespace {

const ::google::protobuf::Descriptor* Bussinesstype_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Bussinesstype_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_center_2fBussinesstype_2eproto() {
  protobuf_AddDesc_center_2fBussinesstype_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "center/Bussinesstype.proto");
  GOOGLE_CHECK(file != NULL);
  Bussinesstype_descriptor_ = file->message_type(0);
  static const int Bussinesstype_offsets_[19] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, nkey_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, strvalue_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, strcode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, nlevel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, pid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, saveyears_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, guaranteeyears_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, nenabled_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, strenddate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, strapplydate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, strvideoenddate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, importuser_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, checkuser_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, importtime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, checktime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, strgrade_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, strrisklevel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, wordtemplate_),
  };
  Bussinesstype_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Bussinesstype_descriptor_,
      Bussinesstype::default_instance_,
      Bussinesstype_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Bussinesstype, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Bussinesstype));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_center_2fBussinesstype_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Bussinesstype_descriptor_, &Bussinesstype::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_center_2fBussinesstype_2eproto() {
  delete Bussinesstype::default_instance_;
  delete Bussinesstype_reflection_;
}

void protobuf_AddDesc_center_2fBussinesstype_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\032center/Bussinesstype.proto\022\010cms_8120\"\365"
    "\002\n\rBussinesstype\022\n\n\002id\030\001 \001(\005\022\014\n\004nKey\030\002 \001"
    "(\005\022\020\n\010strValue\030\003 \001(\t\022\017\n\007strCode\030\004 \001(\t\022\016\n"
    "\006nLevel\030\005 \001(\005\022\013\n\003pid\030\006 \001(\005\022\021\n\tsaveYears\030"
    "\007 \001(\005\022\026\n\016guaranteeYears\030\010 \001(\005\022\020\n\010nEnable"
    "d\030\t \001(\005\022\022\n\nstrEndDate\030\n \001(\t\022\024\n\014strApplyD"
    "ate\030\013 \001(\t\022\027\n\017strVideoEndDate\030\014 \001(\t\022\022\n\nim"
    "portUser\030\r \001(\005\022\021\n\tcheckUser\030\016 \001(\005\022\022\n\nimp"
    "ortTime\030\017 \001(\t\022\021\n\tcheckTime\030\020 \001(\t\022\020\n\010strG"
    "rade\030\021 \001(\t\022\024\n\014strRisklevel\030\022 \001(\t\022\024\n\014word"
    "Template\030\023 \001(\tB>\n(com.hikvision.finance."
    "fms.cms.hpp.centerB\022BussinesstypeProto", 478);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "center/Bussinesstype.proto", &protobuf_RegisterTypes);
  Bussinesstype::default_instance_ = new Bussinesstype();
  Bussinesstype::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_center_2fBussinesstype_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_center_2fBussinesstype_2eproto {
  StaticDescriptorInitializer_center_2fBussinesstype_2eproto() {
    protobuf_AddDesc_center_2fBussinesstype_2eproto();
  }
} static_descriptor_initializer_center_2fBussinesstype_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int Bussinesstype::kIdFieldNumber;
const int Bussinesstype::kNKeyFieldNumber;
const int Bussinesstype::kStrValueFieldNumber;
const int Bussinesstype::kStrCodeFieldNumber;
const int Bussinesstype::kNLevelFieldNumber;
const int Bussinesstype::kPidFieldNumber;
const int Bussinesstype::kSaveYearsFieldNumber;
const int Bussinesstype::kGuaranteeYearsFieldNumber;
const int Bussinesstype::kNEnabledFieldNumber;
const int Bussinesstype::kStrEndDateFieldNumber;
const int Bussinesstype::kStrApplyDateFieldNumber;
const int Bussinesstype::kStrVideoEndDateFieldNumber;
const int Bussinesstype::kImportUserFieldNumber;
const int Bussinesstype::kCheckUserFieldNumber;
const int Bussinesstype::kImportTimeFieldNumber;
const int Bussinesstype::kCheckTimeFieldNumber;
const int Bussinesstype::kStrGradeFieldNumber;
const int Bussinesstype::kStrRisklevelFieldNumber;
const int Bussinesstype::kWordTemplateFieldNumber;
#endif  // !_MSC_VER

Bussinesstype::Bussinesstype()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Bussinesstype::InitAsDefaultInstance() {
}

Bussinesstype::Bussinesstype(const Bussinesstype& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Bussinesstype::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  nkey_ = 0;
  strvalue_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  strcode_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  nlevel_ = 0;
  pid_ = 0;
  saveyears_ = 0;
  guaranteeyears_ = 0;
  nenabled_ = 0;
  strenddate_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  strapplydate_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  strvideoenddate_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  importuser_ = 0;
  checkuser_ = 0;
  importtime_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  checktime_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  strgrade_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  strrisklevel_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  wordtemplate_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Bussinesstype::~Bussinesstype() {
  SharedDtor();
}

void Bussinesstype::SharedDtor() {
  if (strvalue_ != &::google::protobuf::internal::kEmptyString) {
    delete strvalue_;
  }
  if (strcode_ != &::google::protobuf::internal::kEmptyString) {
    delete strcode_;
  }
  if (strenddate_ != &::google::protobuf::internal::kEmptyString) {
    delete strenddate_;
  }
  if (strapplydate_ != &::google::protobuf::internal::kEmptyString) {
    delete strapplydate_;
  }
  if (strvideoenddate_ != &::google::protobuf::internal::kEmptyString) {
    delete strvideoenddate_;
  }
  if (importtime_ != &::google::protobuf::internal::kEmptyString) {
    delete importtime_;
  }
  if (checktime_ != &::google::protobuf::internal::kEmptyString) {
    delete checktime_;
  }
  if (strgrade_ != &::google::protobuf::internal::kEmptyString) {
    delete strgrade_;
  }
  if (strrisklevel_ != &::google::protobuf::internal::kEmptyString) {
    delete strrisklevel_;
  }
  if (wordtemplate_ != &::google::protobuf::internal::kEmptyString) {
    delete wordtemplate_;
  }
  if (this != default_instance_) {
  }
}

void Bussinesstype::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Bussinesstype::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Bussinesstype_descriptor_;
}

const Bussinesstype& Bussinesstype::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_center_2fBussinesstype_2eproto();  return *default_instance_;
}

Bussinesstype* Bussinesstype::default_instance_ = NULL;

Bussinesstype* Bussinesstype::New() const {
  return new Bussinesstype;
}

void Bussinesstype::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0;
    nkey_ = 0;
    if (has_strvalue()) {
      if (strvalue_ != &::google::protobuf::internal::kEmptyString) {
        strvalue_->clear();
      }
    }
    if (has_strcode()) {
      if (strcode_ != &::google::protobuf::internal::kEmptyString) {
        strcode_->clear();
      }
    }
    nlevel_ = 0;
    pid_ = 0;
    saveyears_ = 0;
    guaranteeyears_ = 0;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    nenabled_ = 0;
    if (has_strenddate()) {
      if (strenddate_ != &::google::protobuf::internal::kEmptyString) {
        strenddate_->clear();
      }
    }
    if (has_strapplydate()) {
      if (strapplydate_ != &::google::protobuf::internal::kEmptyString) {
        strapplydate_->clear();
      }
    }
    if (has_strvideoenddate()) {
      if (strvideoenddate_ != &::google::protobuf::internal::kEmptyString) {
        strvideoenddate_->clear();
      }
    }
    importuser_ = 0;
    checkuser_ = 0;
    if (has_importtime()) {
      if (importtime_ != &::google::protobuf::internal::kEmptyString) {
        importtime_->clear();
      }
    }
    if (has_checktime()) {
      if (checktime_ != &::google::protobuf::internal::kEmptyString) {
        checktime_->clear();
      }
    }
  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    if (has_strgrade()) {
      if (strgrade_ != &::google::protobuf::internal::kEmptyString) {
        strgrade_->clear();
      }
    }
    if (has_strrisklevel()) {
      if (strrisklevel_ != &::google::protobuf::internal::kEmptyString) {
        strrisklevel_->clear();
      }
    }
    if (has_wordtemplate()) {
      if (wordtemplate_ != &::google::protobuf::internal::kEmptyString) {
        wordtemplate_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Bussinesstype::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_nKey;
        break;
      }
      
      // optional int32 nKey = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_nKey:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &nkey_)));
          set_has_nkey();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_strValue;
        break;
      }
      
      // optional string strValue = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_strValue:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strvalue()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->strvalue().data(), this->strvalue().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_strCode;
        break;
      }
      
      // optional string strCode = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_strCode:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strcode()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->strcode().data(), this->strcode().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_nLevel;
        break;
      }
      
      // optional int32 nLevel = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_nLevel:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &nlevel_)));
          set_has_nlevel();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_pid;
        break;
      }
      
      // optional int32 pid = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_pid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pid_)));
          set_has_pid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_saveYears;
        break;
      }
      
      // optional int32 saveYears = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_saveYears:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &saveyears_)));
          set_has_saveyears();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_guaranteeYears;
        break;
      }
      
      // optional int32 guaranteeYears = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_guaranteeYears:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &guaranteeyears_)));
          set_has_guaranteeyears();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_nEnabled;
        break;
      }
      
      // optional int32 nEnabled = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_nEnabled:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &nenabled_)));
          set_has_nenabled();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(82)) goto parse_strEndDate;
        break;
      }
      
      // optional string strEndDate = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_strEndDate:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strenddate()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->strenddate().data(), this->strenddate().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(90)) goto parse_strApplyDate;
        break;
      }
      
      // optional string strApplyDate = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_strApplyDate:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strapplydate()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->strapplydate().data(), this->strapplydate().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(98)) goto parse_strVideoEndDate;
        break;
      }
      
      // optional string strVideoEndDate = 12;
      case 12: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_strVideoEndDate:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strvideoenddate()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->strvideoenddate().data(), this->strvideoenddate().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(104)) goto parse_importUser;
        break;
      }
      
      // optional int32 importUser = 13;
      case 13: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_importUser:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &importuser_)));
          set_has_importuser();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(112)) goto parse_checkUser;
        break;
      }
      
      // optional int32 checkUser = 14;
      case 14: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_checkUser:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &checkuser_)));
          set_has_checkuser();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(122)) goto parse_importTime;
        break;
      }
      
      // optional string importTime = 15;
      case 15: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_importTime:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_importtime()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->importtime().data(), this->importtime().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(130)) goto parse_checkTime;
        break;
      }
      
      // optional string checkTime = 16;
      case 16: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_checkTime:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_checktime()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->checktime().data(), this->checktime().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(138)) goto parse_strGrade;
        break;
      }
      
      // optional string strGrade = 17;
      case 17: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_strGrade:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strgrade()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->strgrade().data(), this->strgrade().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(146)) goto parse_strRisklevel;
        break;
      }
      
      // optional string strRisklevel = 18;
      case 18: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_strRisklevel:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strrisklevel()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->strrisklevel().data(), this->strrisklevel().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(154)) goto parse_wordTemplate;
        break;
      }
      
      // optional string wordTemplate = 19;
      case 19: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_wordTemplate:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_wordtemplate()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->wordtemplate().data(), this->wordtemplate().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Bussinesstype::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }
  
  // optional int32 nKey = 2;
  if (has_nkey()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->nkey(), output);
  }
  
  // optional string strValue = 3;
  if (has_strvalue()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strvalue().data(), this->strvalue().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->strvalue(), output);
  }
  
  // optional string strCode = 4;
  if (has_strcode()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strcode().data(), this->strcode().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->strcode(), output);
  }
  
  // optional int32 nLevel = 5;
  if (has_nlevel()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->nlevel(), output);
  }
  
  // optional int32 pid = 6;
  if (has_pid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->pid(), output);
  }
  
  // optional int32 saveYears = 7;
  if (has_saveyears()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->saveyears(), output);
  }
  
  // optional int32 guaranteeYears = 8;
  if (has_guaranteeyears()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->guaranteeyears(), output);
  }
  
  // optional int32 nEnabled = 9;
  if (has_nenabled()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->nenabled(), output);
  }
  
  // optional string strEndDate = 10;
  if (has_strenddate()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strenddate().data(), this->strenddate().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      10, this->strenddate(), output);
  }
  
  // optional string strApplyDate = 11;
  if (has_strapplydate()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strapplydate().data(), this->strapplydate().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      11, this->strapplydate(), output);
  }
  
  // optional string strVideoEndDate = 12;
  if (has_strvideoenddate()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strvideoenddate().data(), this->strvideoenddate().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      12, this->strvideoenddate(), output);
  }
  
  // optional int32 importUser = 13;
  if (has_importuser()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(13, this->importuser(), output);
  }
  
  // optional int32 checkUser = 14;
  if (has_checkuser()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(14, this->checkuser(), output);
  }
  
  // optional string importTime = 15;
  if (has_importtime()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->importtime().data(), this->importtime().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      15, this->importtime(), output);
  }
  
  // optional string checkTime = 16;
  if (has_checktime()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->checktime().data(), this->checktime().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      16, this->checktime(), output);
  }
  
  // optional string strGrade = 17;
  if (has_strgrade()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strgrade().data(), this->strgrade().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      17, this->strgrade(), output);
  }
  
  // optional string strRisklevel = 18;
  if (has_strrisklevel()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strrisklevel().data(), this->strrisklevel().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      18, this->strrisklevel(), output);
  }
  
  // optional string wordTemplate = 19;
  if (has_wordtemplate()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->wordtemplate().data(), this->wordtemplate().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      19, this->wordtemplate(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Bussinesstype::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }
  
  // optional int32 nKey = 2;
  if (has_nkey()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->nkey(), target);
  }
  
  // optional string strValue = 3;
  if (has_strvalue()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strvalue().data(), this->strvalue().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->strvalue(), target);
  }
  
  // optional string strCode = 4;
  if (has_strcode()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strcode().data(), this->strcode().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->strcode(), target);
  }
  
  // optional int32 nLevel = 5;
  if (has_nlevel()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->nlevel(), target);
  }
  
  // optional int32 pid = 6;
  if (has_pid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->pid(), target);
  }
  
  // optional int32 saveYears = 7;
  if (has_saveyears()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->saveyears(), target);
  }
  
  // optional int32 guaranteeYears = 8;
  if (has_guaranteeyears()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->guaranteeyears(), target);
  }
  
  // optional int32 nEnabled = 9;
  if (has_nenabled()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->nenabled(), target);
  }
  
  // optional string strEndDate = 10;
  if (has_strenddate()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strenddate().data(), this->strenddate().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->strenddate(), target);
  }
  
  // optional string strApplyDate = 11;
  if (has_strapplydate()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strapplydate().data(), this->strapplydate().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->strapplydate(), target);
  }
  
  // optional string strVideoEndDate = 12;
  if (has_strvideoenddate()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strvideoenddate().data(), this->strvideoenddate().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        12, this->strvideoenddate(), target);
  }
  
  // optional int32 importUser = 13;
  if (has_importuser()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(13, this->importuser(), target);
  }
  
  // optional int32 checkUser = 14;
  if (has_checkuser()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(14, this->checkuser(), target);
  }
  
  // optional string importTime = 15;
  if (has_importtime()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->importtime().data(), this->importtime().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        15, this->importtime(), target);
  }
  
  // optional string checkTime = 16;
  if (has_checktime()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->checktime().data(), this->checktime().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        16, this->checktime(), target);
  }
  
  // optional string strGrade = 17;
  if (has_strgrade()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strgrade().data(), this->strgrade().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        17, this->strgrade(), target);
  }
  
  // optional string strRisklevel = 18;
  if (has_strrisklevel()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strrisklevel().data(), this->strrisklevel().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        18, this->strrisklevel(), target);
  }
  
  // optional string wordTemplate = 19;
  if (has_wordtemplate()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->wordtemplate().data(), this->wordtemplate().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        19, this->wordtemplate(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Bussinesstype::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }
    
    // optional int32 nKey = 2;
    if (has_nkey()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->nkey());
    }
    
    // optional string strValue = 3;
    if (has_strvalue()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->strvalue());
    }
    
    // optional string strCode = 4;
    if (has_strcode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->strcode());
    }
    
    // optional int32 nLevel = 5;
    if (has_nlevel()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->nlevel());
    }
    
    // optional int32 pid = 6;
    if (has_pid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->pid());
    }
    
    // optional int32 saveYears = 7;
    if (has_saveyears()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->saveyears());
    }
    
    // optional int32 guaranteeYears = 8;
    if (has_guaranteeyears()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->guaranteeyears());
    }
    
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional int32 nEnabled = 9;
    if (has_nenabled()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->nenabled());
    }
    
    // optional string strEndDate = 10;
    if (has_strenddate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->strenddate());
    }
    
    // optional string strApplyDate = 11;
    if (has_strapplydate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->strapplydate());
    }
    
    // optional string strVideoEndDate = 12;
    if (has_strvideoenddate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->strvideoenddate());
    }
    
    // optional int32 importUser = 13;
    if (has_importuser()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->importuser());
    }
    
    // optional int32 checkUser = 14;
    if (has_checkuser()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->checkuser());
    }
    
    // optional string importTime = 15;
    if (has_importtime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->importtime());
    }
    
    // optional string checkTime = 16;
    if (has_checktime()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->checktime());
    }
    
  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    // optional string strGrade = 17;
    if (has_strgrade()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->strgrade());
    }
    
    // optional string strRisklevel = 18;
    if (has_strrisklevel()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->strrisklevel());
    }
    
    // optional string wordTemplate = 19;
    if (has_wordtemplate()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->wordtemplate());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Bussinesstype::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Bussinesstype* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Bussinesstype*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Bussinesstype::MergeFrom(const Bussinesstype& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_nkey()) {
      set_nkey(from.nkey());
    }
    if (from.has_strvalue()) {
      set_strvalue(from.strvalue());
    }
    if (from.has_strcode()) {
      set_strcode(from.strcode());
    }
    if (from.has_nlevel()) {
      set_nlevel(from.nlevel());
    }
    if (from.has_pid()) {
      set_pid(from.pid());
    }
    if (from.has_saveyears()) {
      set_saveyears(from.saveyears());
    }
    if (from.has_guaranteeyears()) {
      set_guaranteeyears(from.guaranteeyears());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_nenabled()) {
      set_nenabled(from.nenabled());
    }
    if (from.has_strenddate()) {
      set_strenddate(from.strenddate());
    }
    if (from.has_strapplydate()) {
      set_strapplydate(from.strapplydate());
    }
    if (from.has_strvideoenddate()) {
      set_strvideoenddate(from.strvideoenddate());
    }
    if (from.has_importuser()) {
      set_importuser(from.importuser());
    }
    if (from.has_checkuser()) {
      set_checkuser(from.checkuser());
    }
    if (from.has_importtime()) {
      set_importtime(from.importtime());
    }
    if (from.has_checktime()) {
      set_checktime(from.checktime());
    }
  }
  if (from._has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    if (from.has_strgrade()) {
      set_strgrade(from.strgrade());
    }
    if (from.has_strrisklevel()) {
      set_strrisklevel(from.strrisklevel());
    }
    if (from.has_wordtemplate()) {
      set_wordtemplate(from.wordtemplate());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Bussinesstype::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Bussinesstype::CopyFrom(const Bussinesstype& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Bussinesstype::IsInitialized() const {
  
  return true;
}

void Bussinesstype::Swap(Bussinesstype* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(nkey_, other->nkey_);
    std::swap(strvalue_, other->strvalue_);
    std::swap(strcode_, other->strcode_);
    std::swap(nlevel_, other->nlevel_);
    std::swap(pid_, other->pid_);
    std::swap(saveyears_, other->saveyears_);
    std::swap(guaranteeyears_, other->guaranteeyears_);
    std::swap(nenabled_, other->nenabled_);
    std::swap(strenddate_, other->strenddate_);
    std::swap(strapplydate_, other->strapplydate_);
    std::swap(strvideoenddate_, other->strvideoenddate_);
    std::swap(importuser_, other->importuser_);
    std::swap(checkuser_, other->checkuser_);
    std::swap(importtime_, other->importtime_);
    std::swap(checktime_, other->checktime_);
    std::swap(strgrade_, other->strgrade_);
    std::swap(strrisklevel_, other->strrisklevel_);
    std::swap(wordtemplate_, other->wordtemplate_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Bussinesstype::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Bussinesstype_descriptor_;
  metadata.reflection = Bussinesstype_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace cms_8120

// @@protoc_insertion_point(global_scope)
