// AtlDemo.idl : IDL source for AtlDemo
//

// This file will be processed by the MIDL tool to
// produce the type library (AtlDemo.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(127943FC-60A0-4480-82F2-CA78C9C03874),
	dual,
	nonextensible,
	helpstring("IIAtlDemoCtrl Interface"),
	pointer_default(unique)
]
interface IIAtlDemoCtrl : IDispatch{
    [id(1), helpstring("method Test")] HRESULT Test([in] BSTR strXml, [in] LONG nData, [out,retval] LONG* lReturn);
};
[
	uuid(18AD0E93-3DF5-40D1-BD6C-554F9C8315D5),
	version(1.0),
	helpstring("AtlDemo 1.0 Type Library")
]
library AtlDemoLib
{
	importlib("stdole2.tlb");
	[
		uuid(ECB057BA-98E9-494B-B11B-70B2AC8214EB),
		helpstring("_IIAtlDemoCtrlEvents Interface")
	]
	dispinterface _IIAtlDemoCtrlEvents
	{
		properties:
		methods:
            [id(1), helpstring("method MsgNotify")] HRESULT MsgNotify([in] LONG lMsgId, [in] BSTR szDetail);
    };
	[
		uuid(8F55A11E-35B9-4B5F-98BD-53502C1590DD),
		helpstring("IAtlDemoCtrl Class")
	]
	coclass IAtlDemoCtrl
	{
		[default] interface IIAtlDemoCtrl;
		[default, source] dispinterface _IIAtlDemoCtrlEvents;
	};
};
