//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ServiceWatchdog.rc
//
#pragma once
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DLG_CENTER_PROCESSOR_CFG    104
#define IDD_DLG_COLLECTOR_PROCESSOR_CFG 105
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       129
#define IDR_MENU_ICON_NOTIFY            129
#define IDD_DIALOG_MAIN                 130
#define IDB_BITMAP_RESTART_ALL          164
#define IDB_BITMAP_EXIT                 166
#define IDB_BITMAP_BLUE_EXIT            166
#define IDB_BITMAP_MINIMIZE             167
#define IDB_BITMAP_BLUE_MINIMIZE        167
#define IDB_BITMAP_MAIN                 168
#define IDB_BITMAP_BLUE_MAIN            168
#define IDB_BITMAP_LIST_HEADER          171
#define IDB_BITMAP_ICON_START           173
#define IDI_ICON1                       174
#define IDB_BITMAP1                     176
#define IDB_BITMAP_MAIN_NOLOGO          176
#define IDB_BITMAP_BLUE_MAIN_NOLOGO     176
#define IDD_DIALOG_VIEWINFO             181
#define IDI_ICON2                       182
#define IDI_ICON_IMG                    182
#define IDB_BITMAP_MAIN_MODIFY          183
#define IDB_BITMAP_BLUE_MAIN_MODIFY     183
#define IDB_BITMAP2                     187
#define IDB_BITMAP_SERVER_LIST          189
#define IDB_BITMAP_BLUE_SERVER_LIST     189
#define IDB_BITMAP_MESSIGE              190
#define IDB_BITMAP_BLUE_MESSIGE         190
#define IDR_MENU_SERIVCE                196
#define IDR_MENU_SERVICE                196
#define IDB_BITMAP_TAB_CONTROL          198
#define IDB_BITMAP3                     199
#define IDB_BITMAP_BLACK_RED_MAIN_MODIFY 200
#define IDB_BITMAP_BLACK_RED_EXIT       201
#define IDB_BITMAP4                     202
#define IDB_BITMAP_BLACK_RED_MINIMIZE   202
#define IDB_BITMAP_RED_BLACK_EXIT       203
#define IDB_BITMAP_RED_BLACK_MAIN_MODIFY 204
#define IDB_BITMAP_RED_BLACK_MINIMIZE   205
#define IDB_BITMAP_RED_BLACK_MAIN       206
#define IDB_BITMAP_RED_BLACK_MAIN_NOLOGO 207
#define IDB_BITMAP_RED_BLACK_MESSIGE    209
#define IDB_BITMAP_RED_BLACK_SERVER_LIST 210
#define IDB_BITMAP5                     214
#define IDB_BITMAP_HEADER               214
#define IDD_DIALOG_CONFIG               215
#define IDB_BITMAP_RED_BLACK_SERVER_CFG 217
#define IDB_BITMAP6                     218
#define IDB_BITMAP_BLUE_SERVER_CFG      218
#define IDD_DLG_COPY                    219
#define IDC_LIST1                       1003
#define IDC_LIST_VIEW_INSTANT_INFO      1003
#define IDC_LIST_SERVICE                1004
#define IDC_TAB_VIEWCONTROL             1006
#define IDC_BUTTON_SERVICE_LIST         1007
#define IDC_BUTTON_CONFIG               1008
#define IDC_LOGO                        1013
#define IDC_IP_ADDR_DC                  1014
#define IDC_EDIT_PORT_DC                1015
#define IDC_IP_ADDR_LOCAL               1016
#define IDC_EDIT_PORT_LOCAL             1017
#define IDC_CHECK_SCHOOL                1018
#define IDC_BTN_SAVE                    1019
#define IDC_BUTTON_RESTART_ALL_SERVICE  1020
#define IDC_BTN_CFG_DESC                1020
#define IDC_BUTTON_STOP_ALL_SERVICE     1021
#define IDC_BTN_OPEN_DIR                1021
#define IDC_BUTTON_INSTANT_SHOW_INFO    1022
#define IDC_STAT_DESC                   1022
#define IDC_STAT_ONE                    1023
#define IDC_STAT_TWO                    1024
#define IDC_STAT_THREE                  1025
#define IDC_STAT_FOUR                   1026
#define IDC_BTN_COPY                    1027
#define IDC_BTN_OK                      1028
#define IDC_BTN_CANCEL                  1029
#define IDC_EDIT_IP                     1030
#define IDC_EDIT_PORT                   1031
#define IDC_EDIT_LOCAL_IP               1032
#define IDC_BTN_ALL_SEL                 1033
#define IDC_BUTTON2                     1034
#define IDC_BTN_ALL_UNSELECT            1034
#define IDC_IP_ADDR_ALARM_IP            1035
#define IDC_IP_ADDR_ALARM_PORT          1036
#define IDC_IP_ADDR_LOCAL_IP            1037
#define IDC_IP_ADDR_LOCAL_PORT          1038
#define IDC_BTN_CENTER_CFG_SAVE         1039
#define IDC_BTN_CENTER_CFG_RESET        1040
#define IDC_MINIMIZE                    1057
#define IDC_EXIT                        1058
#define IDC_APP_STAT                    1061
#define IDC_START_SERVICE               1071
#define USER_LIST_ID_BASE               7000
#define ID_ICONNOTIFY_32772             32772
#define ID_ICONNOTIFY_32773             32773
#define ID_ICONNOTIFY_SHOW_WINDOW       32774
#define ID_ICONNOTIFY_HIDE_WINDOWS      32775
#define ID_ICONNOTIFY_HIDE_WINDOW       32776
#define ID_ICONNOTIFY_EXIT              32777
#define ID_SERVICECONTROL_32780         32780
#define ID_SERVICECONTROL_32781         32781
#define ID_SERVICECONTROL_32782         32782
#define ID_SERVICECONTROL_32783         32783
#define ID_Menu                         32784
#define ID_SERVICECONTROL_32785         32785
#define ID_SERVICECONTROL_32786         32786
#define ID_SERVICECONTROL_START         32787
#define ID_SERVICECONTROL_STOP          32788
#define ID_SERVICECONTROL_INSTALL       32789
#define ID_SERVICECONTROL_UNINSTALL     32790
#define ID_SERVICECONTROL_CONFIG        32791
#define ID_SERVICECONTROL_RUN_DIR       32792
#define ID_SERVICECONTROL_32793         32793
#define ID_SERVICECONTROL_32794         32794
#define ID_SERVICECONTROL_ALL_STOP      32795
#define ID_SERVICECONTROL_ALL_START     32796
#define ID_SERVICECONTROL_32797         32797
#define ID_SERVICECONTROL_MESSAGE       32798
#define ID_SERVICECONTROL_32799         32799
#define ID_SERVICECONTROL_RESTART       32800
#define ID_Menu32801                    32801
#define ID_SERVICECONTROL_ALL_UNINSTALL 32802
#define ID_Menu32803                    32803
#define ID_SERVICECONTROL_ALL_INSTALL   32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        220
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
