//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FMSClient.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_FMSCLIENT_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_DLG_LOGIN                   129
#define IDD_DLG_SPLASH                  130
#define IDD_DLG_NAVIBAR                 131
#define IDD_DLG_BOTTOM                  132
#define IDD_DLG_BUSINESSMANAGE          133
#define IDD_DLG_BUSINESSLIST            134
#define IDD_DLG_CONFIG                  135
#define IDD_DLG_PREVIEW_CRTL            136
#define IDD_DLG_RECNAMEINFO             137
#define IDD_DLG_PLAYBACK_CTRL           138
#define IDD_DLG_HISTORY_LIST            143
#define IDD_DLG_BUSINESS_INFO           144
#define IDD_DLG_CHANGEPWD               145
#define IDR_MENU_ICON_NOTIFY            146
#define IDD_DLG_EDIT_FILENAME           147
#define IDD_DLG_WORDTEMPLATE            148
#define IDC_BUTTON1                     1000
#define IDC_STATIC_BUSINESSINFO         1003
#define IDC_STATIC_BUSINESSID           1004
#define IDC_EDIT_BUSINESSID             1005
#define IDC_STATIC_BUSINESSLOCATION     1006
#define IDC_EDIT_CUSTOMERNAME           1007
#define IDC_COMBO_BUSINESSLOCATION      1008
#define IDC_EDIT_BUSINESSNUM            1008
#define IDC_STATIC_CUSTOMERNAME         1009
#define IDC_EDIT_CUSTOMERPHONE          1010
#define IDC_STATIC_BUSINESSNUM          1010
#define IDC_STATIC_CUSTOMERPHONE        1011
#define IDC_EDIT_PRODUCTCODE            1012
#define IDC_STATIC_IDTYPE               1013
#define IDC_EDIT_IDNUMBER               1014
#define IDC_STATIC_IDNUMBER             1015
#define IDC_COMBO_IDTYPE                1016
#define IDC_STATIC_PRODUCTINFO          1017
#define IDC_BTN_OSD                     1018
#define IDC_STATIC_RECORDINFO           1018
#define IDC_STATIC_PRODUCTTYPE          1019
#define IDC_COMBO_PRODUCTTYPE           1020
#define IDC_STATIC_PRODUCTTYPE2         1021
#define IDC_COMBO_PRODUCTNAME           1022
#define IDC_STATIC_PRODUCTCODE          1023
#define IDC_EDIT_ISSUER                 1024
#define IDC_STATIC_ISSUER               1025
#define IDC_EDIT_PURCHASEAMOUNT         1026
#define IDC_STATIC_PURCHASEAMOUNT       1027
#define IDC_STATIC_SALESMANINFO         1028
#define IDC_STATIC_SALESMANNAME1        1029
#define IDC_STATIC_SALESMANNAME2        1030
#define IDC_STATIC_SALESMANID1          1031
#define IDC_STATIC_SALESMANID2          1032
#define IDC_STATIC_RECLIST              1033
#define IDC_LIST_RECORDS                1034
#define IDC_BTN_RECENT                  1035
#define IDC_BTN_BUSINESSINFO            1035
#define IDC_BTN_EXCEPTION               1036
#define IDC_BTN_BUSINESSINFO2           1036
#define IDC_BTN_PRODUCTINFO             1036
#define IDC_BTN_TOTAL                   1037
#define IDC_BTN_SALESMANINFO            1037
#define IDC_BTN_RECORDINFO              1037
#define IDC_LIST_RECENT                 1038
#define IDC_LIST_EXCEPTION              1039
#define IDC_LIST_TOTAL                  1040
#define IDC_BTN_EDITRECNAME             1040
#define IDC_BTN_UPLOAD                  1041
#define IDC_STATIC_RECNAME              1041
#define IDC_BTN_REFRESH                 1042
#define IDC_EDIT_RECNAME                1042
#define IDC_BTN_EXPORT                  1043
#define IDC_STATIC_COPYRIGHT            1044
#define IDC_STATIC_VERSION              1045
#define IDC_BTN_PRINT                   1046
#define IDC_BTN_SUBMIT                  1047
#define IDC_BTN_RESET                   1048
#define IDC_STATIC_BLANK1               1049
#define IDC_STATIC_BLANK2               1050
#define IDC_STATIC_BLANK3               1051
#define IDC_BTN_HISTORYLIST             1052
#define IDC_BTN_WORDS                   1053
#define IDC_STATIC_STARTTIME            1056
#define IDC_STATIC_ENDTIME              1057
#define IDC_DATETIME_START              1058
#define IDC_DATETIME_END                1059
#define IDC_BTN_QUERY                   1060
#define IDC_STATIC_CONSUMERNAME         1061
#define IDC_STATIC_PRODUCTNAME          1062
#define IDC_LIST_HISTORYLIST            1062
#define IDC_EDIT_CONSUMERNAME           1065
#define IDC_EDIT_PRODUCTNAME            1066
#define IDC_BTN_BASIC_PARM              1066
#define IDC_STATIC_BASIC_PARM           1067
#define IDC_STATIC_DEFAULT_FOLDER       1068
#define IDC_EDIT_DEFAULT_FOLDER         1069
#define IDC_BTN_CHANGE_DIR              1070
#define IDC_BTN_OPEN_FOLDER             1071
#define IDC_STATIC_SALESMAN_INFO        1072
#define IDC_BTN_SALESMAN_INFO           1073
#define IDC_STATIC_DEFAULT_IPC          1074
#define IDC_EDIT_UPLOADTIMESTART        1075
#define IDC_STATIC_UPLOADTIME           1076
#define IDC_COMBO_DEFAULT_IPC           1077
#define IDC_CHECK_OPEN                  1078
#define IDC_CHECK_CLOSE                 1079
#define IDC_STATIC_AUDIOSET             1080
#define IDC_STATIC_UPLOAD_INFO          1081
#define IDC_BTN_SAVE                    1081
#define IDC_BTN_UPLOAD_INFO             1082
#define IDC_EDIT_NOW_PWD                1082
#define IDC_EDIT_RECORDTIME             1083
#define IDC_EDIT_NEW_PWD                1083
#define IDC_STATIC_RECORDTIME           1084
#define IDC_EDIT_NEW_PWD2               1084
#define IDC_STATIC_AND                  1085
#define IDC_STATIC_NOW_PWD              1085
#define IDC_EDIT_UPLOADTIMEEND          1086
#define IDC_STATIC_NEW_PWD              1086
#define IDC_STATIC_NEW_PWD2             1087
#define IDC_STATIC_SYSTEM_INFO          1087
#define IDC_BTN_SYSTEM_INFO             1088
#define IDC_STATIC_STARTUPSET           1089
#define IDC_CHECK_STARTUP               1090
#define IDC_STATIC_CLOSE                1091
#define IDC_CHECK_EXIT                  1092
#define IDC_CHECK_TRAY                  1093
#define ID_RESET                        1094
#define IDC_EDIT_FILENAME               1095
#define IDC_STATIC_FILENAME             1096
#define IDC_STATIC_PRODUCTNAME1         1097
#define IDC_STATIC_PRODUCTNAME2         1098
#define IDC_STATIC_PRODUCTWORD          1099
#define IDC_EDIT_PRODUCTWORD            1101
#define IDC_BTN_STATE                   1102
#define IDC_LISTBOX_PRODUCTCODE         1103
#define IDC_STATIC_MINUTE               1104
#define IDC_STATIC_BLANK4               1106
#define IDC_COMBO1                      1107
#define IDC_COMBO_BUSINESSID            1107
#define ID_ICONNOTIFY_32771             32771
#define ID_ICONNOTIFY_32772             32772
#define ID_ICONNOTIFY_SHOW_WINDOW       32773
#define ID_ICONNOTIFY_EXIT              32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
